### PR TITLE
Fix issues/364

### LINKED ISSUE #364: Publisher failed to send messages to durable topic after broker restart
**Description:**
Following INFO prints for each message and drop the message.

`[io.ballerina.messaging.broker.core.BrokerImpl] - Dropping message since no queues found for routing key Topic1 in Exchange{name='amq.topic', type=topic}`

**Steps to reproduce:**

- Add durable topic subscriber
- Send 10 messages to the topic
- Restart the broker after subscriber successfully receive messages
- Send another 10 messages without adding a subscriber

### PR DESCRIPTION
**Pull request by indikasampath2000**
Messages publishing to a durable topic drop after broker restart fix in this PR. The BindingsRegistry class modified to act as an observer and notify to the TopicExchange when bind, unbind and retrieve bindings from the database.

Resolves #364 

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: modules/broker-core/src/main/java/io/ballerina/messaging/broker/core/BindingsRegistry.java [hunk 1]
```diff
@@ -43,38 +51,58 @@
 
     private final BindingDeleteListener bindingDeleteListener;
 
+    private List<BindingsRegistryListener> bindingsRegistryListeners;
+
+    private final ReadWriteLock lock;
```
Comment (a5anka) [inline modules/broker-core/src/main/java/io/ballerina/messaging/broker/core/BindingsRegistry.java]: Why have we introduced a lock in this class?

File: modules/broker-core/src/main/java/io/ballerina/messaging/broker/core/BindingsRegistry.java [hunk 2]
```diff
@@ -43,38 +51,58 @@
...
-        Queue queue = queueHandler.getQueue();
-        Binding binding = new Binding(queue, bindingKey, arguments);
-        boolean success = bindingSet.add(binding);
-
-        if (success) {
-            queueHandler.addBinding(binding, bindingDeleteListener);
-            if (queue.isDurable()) {
-                bindingDao.persist(exchange.getName(), binding);
+            ValidationException {
+        lock.writeLock().lock();
```
Comment (a5anka) [inline modules/broker-core/src/main/java/io/ballerina/messaging/broker/core/BindingsRegistry.java]: We don't need a lock here since BrokerImpl holds a lock before propagating the call here.

File: modules/broker-core/src/main/java/io/ballerina/messaging/broker/core/BindingsRegistry.java [hunk 3]
```diff
@@ -43,38 +51,58 @@
...
         }
     }
 
     void unbind(Queue queue, String routingKey) throws BrokerException {
-        BindingSet bindingSet = bindingPatternToBindingsMap.get(routingKey);
-        if (queue.isDurable()) {
-            bindingDao.delete(queue.getName(), routingKey, exchange.getName());
-        }
-        bindingSet.remove(queue);
+        lock.writeLock().lock();
```
Comment (a5anka) [inline modules/broker-core/src/main/java/io/ballerina/messaging/broker/core/BindingsRegistry.java]: This also does not need a lock since BrokerImpl holds a lock before propagating the call here.

**Comment by a5anka** [comment]
Shall we create an issue to track the test automation for this scenario?

File: modules/broker-core/src/main/java/io/ballerina/messaging/broker/core/BindingsRegistry.java (hunk 1 above)
Comment (indikasampath2000) [reply modules/broker-core/src/main/java/io/ballerina/messaging/broker/core/BindingsRegistry.java]: Fixed in cd6b801

File: modules/broker-core/src/main/java/io/ballerina/messaging/broker/core/BindingsRegistry.java (hunk 2 above)
Comment (indikasampath2000) [reply modules/broker-core/src/main/java/io/ballerina/messaging/broker/core/BindingsRegistry.java]: Fixed in cd6b801

File: modules/broker-core/src/main/java/io/ballerina/messaging/broker/core/BindingsRegistry.java (hunk 3 above)
Comment (indikasampath2000) [reply modules/broker-core/src/main/java/io/ballerina/messaging/broker/core/BindingsRegistry.java]: Fixed in cd6b801

**Comment by indikasampath2000** [comment]
+1. An issue created #371.
